// PM2 Ecosystem — runs 4 Node.js backend instances on ports 5001-5004
// Each instance handled by Nginx upstream load balancer
module.exports = {
  apps: [
    {
      name: 'earnhub-api-1',
      script: 'src/server.js',
      cwd: '/var/www/earnhub/backend',
      env: { PORT: 5001, NODE_ENV: 'production' },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/earnhub-1-error.log',
      out_file: '/var/log/pm2/earnhub-1-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'earnhub-api-2',
      script: 'src/server.js',
      cwd: '/var/www/earnhub/backend',
      env: { PORT: 5002, NODE_ENV: 'production' },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/earnhub-2-error.log',
      out_file: '/var/log/pm2/earnhub-2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'earnhub-api-3',
      script: 'src/server.js',
      cwd: '/var/www/earnhub/backend',
      env: { PORT: 5003, NODE_ENV: 'production' },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/earnhub-3-error.log',
      out_file: '/var/log/pm2/earnhub-3-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts: 10,
    },
    {
      name: 'earnhub-api-4',
      script: 'src/server.js',
      cwd: '/var/www/earnhub/backend',
      env: { PORT: 5004, NODE_ENV: 'production' },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '512M',
      error_file: '/var/log/pm2/earnhub-4-error.log',
      out_file: '/var/log/pm2/earnhub-4-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      restart_delay: 3000,
      max_restarts: 10,
    },
  ],
};
