const mongoose = require('mongoose');
require('dotenv').config();

const { Challenge } = require('../src/models/Challenge');

const tomorrow = () => {
  const now = new Date();
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate() + 1));
};

const dailyUntilTomorrow = tomorrow();

const allChallenges = [
  {
    title: 'Daily Login',
    description: 'Log in today to stay active and earn your daily bonus.',
    type: 'login',
    eventType: 'login',
    targetCount: 1,
    xpReward: 20,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 1,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Complete a Task',
    description: 'Finish any cash task from the tasks section.',
    type: 'task',
    eventType: 'task_complete',
    targetCount: 1,
    xpReward: 30,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 2,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Complete a Survey',
    description: 'Finish any survey from the surveys section.',
    type: 'survey',
    eventType: 'survey_complete',
    targetCount: 1,
    xpReward: 25,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 3,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Use an Offerwall',
    description: 'Complete any offer from any offerwall provider.',
    type: 'offerwall',
    eventType: 'offerwall_complete',
    targetCount: 1,
    xpReward: 35,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 4,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: '3-Task Grind',
    description: 'Complete 3 tasks in a single day.',
    type: 'task',
    eventType: 'task_complete_3',
    targetCount: 1,
    xpReward: 80,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 5,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: '5-Task Master',
    description: 'Complete 5 tasks today.',
    type: 'task',
    eventType: 'task_complete_5',
    targetCount: 1,
    xpReward: 150,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 6,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Survey Trio',
    description: 'Complete 3 surveys in one day.',
    type: 'survey',
    eventType: 'survey_complete_3',
    targetCount: 1,
    xpReward: 70,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 7,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Refer a Friend',
    description: 'Successfully refer someone who joins the platform.',
    type: 'referral',
    eventType: 'referral',
    targetCount: 1,
    xpReward: 100,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 8,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Referral Trio',
    description: 'Bring in 3 verified referrals.',
    type: 'referral',
    eventType: 'referral_3',
    targetCount: 1,
    xpReward: 400,
    rewardUSD: 1.0,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 9,
    expiresAt: null,
  },
  {
    title: 'Apply for a Job',
    description: 'Submit an application for any job listing.',
    type: 'job',
    eventType: 'job_apply',
    targetCount: 1,
    xpReward: 40,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 10,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Post a Job',
    description: 'Create a job listing to help others find work.',
    type: 'job',
    eventType: 'job_post',
    targetCount: 1,
    xpReward: 60,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 11,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Top Up',
    description: 'Make any deposit to boost your balance.',
    type: 'wallet',
    eventType: 'deposit',
    targetCount: 1,
    xpReward: 50,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 12,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: '3-Day Streak',
    description: 'Log in 3 days in a row.',
    type: 'login',
    eventType: 'daily_login_streak_3',
    targetCount: 1,
    xpReward: 75,
    rewardUSD: 0.1,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 13,
    expiresAt: null,
  },
  {
    title: '7-Day Streak',
    description: 'Log in 7 days in a row.',
    type: 'login',
    eventType: 'daily_login_streak_7',
    targetCount: 1,
    xpReward: 200,
    rewardUSD: 0.5,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 14,
    expiresAt: null,
  },
  {
    title: '14-Day Streak',
    description: 'Two weeks straight.',
    type: 'login',
    eventType: 'login_streak_14',
    targetCount: 1,
    xpReward: 500,
    rewardUSD: 1.0,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 15,
    expiresAt: null,
  },
  {
    title: '30-Day Streak',
    description: 'A full month of daily logins.',
    type: 'login',
    eventType: 'login_streak_30',
    targetCount: 1,
    xpReward: 1500,
    rewardUSD: 3.0,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 16,
    expiresAt: null,
  },
  {
    title: 'Complete Your Profile',
    description: 'Fill in all profile fields.',
    type: 'profile',
    eventType: 'profile_complete',
    targetCount: 1,
    xpReward: 100,
    rewardUSD: 0.15,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 17,
    expiresAt: null,
  },
  {
    title: 'First Withdrawal',
    description: 'Complete your first withdrawal.',
    type: 'withdrawal',
    eventType: 'first_withdrawal',
    targetCount: 1,
    xpReward: 200,
    rewardUSD: 0,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 18,
    expiresAt: null,
  },
  {
    title: 'First Dollar',
    description: 'Reach $1.00 in wallet balance.',
    type: 'earnings',
    eventType: 'earning_milestone_1usd',
    targetCount: 1,
    xpReward: 250,
    rewardUSD: 0.1,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 19,
    expiresAt: null,
  },
  {
    title: '$5 Earner',
    description: 'Accumulate $5.00 in wallet balance.',
    type: 'earnings',
    eventType: 'earning_milestone_5usd',
    targetCount: 1,
    xpReward: 500,
    rewardUSD: 0.25,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 20,
    expiresAt: null,
  },
  {
    title: 'Share Your Referral Link',
    description: 'Share your referral link via any channel.',
    type: 'referral',
    eventType: 'share_referral',
    targetCount: 1,
    xpReward: 15,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 21,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Weekly Grinder',
    description: 'Keep your weekly streak going.',
    type: 'login',
    eventType: 'daily_login_streak_7',
    targetCount: 1,
    xpReward: 300,
    rewardUSD: 0.75,
    isActive: true,
    isDaily: false,
    resetDaily: false,
    sortOrder: 22,
    expiresAt: null,
  },
  {
    title: 'Connect Your Wallet',
    description: 'Connect a payout or wallet destination.',
    type: 'wallet',
    eventType: 'wallet_connect',
    targetCount: 1,
    xpReward: 25,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 23,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Send a Chat Message',
    description: 'Send a message in the chat system.',
    type: 'chat',
    eventType: 'chat_message',
    targetCount: 1,
    xpReward: 25,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 24,
    expiresAt: dailyUntilTomorrow,
  },
  {
    title: 'Offerwall Runner',
    description: 'Complete an offerwall reward today.',
    type: 'offerwall',
    eventType: 'offerwall_complete',
    targetCount: 1,
    xpReward: 45,
    rewardUSD: 0,
    isActive: true,
    isDaily: true,
    resetDaily: true,
    sortOrder: 25,
    expiresAt: dailyUntilTomorrow,
  },
];

async function seed() {
  const mongoUri = process.env.MONGODB_URI || process.env.MONGO_URI;
  if (!mongoUri) {
    throw new Error('MONGODB_URI is not configured');
  }

  await mongoose.connect(mongoUri);
  await Challenge.deleteMany({});
  const inserted = await Challenge.insertMany(allChallenges);
  console.log(`Seeded ${inserted.length} challenges`);
  process.exit(0);
}

seed().catch((error) => {
  console.error(error);
  process.exit(1);
});
