const CATEGORY_PROVIDERS = {
  remote_jobs: {
    key: 'remote_jobs',
    title: 'Remote Jobs',
    description: 'Different job APIs and ATS sources for remote work discovery.',
    providers: [
      {
        key: 'remotive',
        name: 'Remotive',
        description: 'Remote engineering, design, support, and marketing jobs.',
        integrationType: 'api',
        access: 'internal_feed',
        badge: 'Live API',
      },
      {
        key: 'jobicy',
        name: 'Jobicy',
        description: 'Curated remote job feed across global categories.',
        integrationType: 'api',
        access: 'internal_feed',
        badge: 'Live API',
      },
      {
        key: 'adzuna',
        name: 'Adzuna',
        description: 'Additional external jobs for expansion when API keys are added.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'greenhouse',
        name: 'Greenhouse',
        description: 'ATS integration target for pulling company-hosted jobs.',
        integrationType: 'ats',
        access: 'planned',
        badge: 'ATS',
      },
      {
        key: 'lever',
        name: 'Lever',
        description: 'ATS integration target for startup and growth-company jobs.',
        integrationType: 'ats',
        access: 'planned',
        badge: 'ATS',
      },
    ],
  },
  surveys: {
    key: 'surveys',
    title: 'Paid Surveys',
    description: 'Survey APIs and survey walls grouped separately from other earning modules.',
    providers: [
      {
        key: 'cpx',
        name: 'CPX Research',
        description: 'High-paying surveys from global brands with automatic reward callbacks.',
        integrationType: 'api',
        access: 'signed_wall',
        badge: 'Live',
      },
      {
        key: 'bitlabs',
        name: 'BitLabs',
        description: 'Premium survey wall with fast payout support.',
        integrationType: 'api',
        access: 'signed_wall',
        badge: 'Live',
      },
      {
        key: 'tap_research',
        name: 'Tap Research',
        description: 'Survey API target for mobile and web opinion offers.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'theoremreach',
        name: 'TheoremReach',
        description: 'Survey inventory for broad demographic coverage.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'pollfish',
        name: 'Pollfish',
        description: 'High-quality survey inventory for opinion-based monetization.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Priority',
      },
      {
        key: 'offertoro',
        name: 'OfferToro Surveys',
        description: 'Survey and offer inventory that can complement core providers.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'wannads_survey',
        name: 'Wannads Surveys',
        description: 'Survey-style rewarded inventory for expansion.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'prime_opinion',
        name: 'Prime Opinion',
        description: 'External survey platform reference for future partner routing.',
        integrationType: 'external',
        access: 'planned',
        badge: 'Research',
      },
    ],
  },
  microtasks: {
    key: 'microtasks',
    title: 'Microtasks',
    description: 'Separate APIs and partner platforms for task-based earning.',
    providers: [
      {
        key: 'mturk',
        name: 'MTurk API',
        description: 'Amazon Mechanical Turk task ecosystem.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
        externalUrl: 'https://www.mturk.com',
      },
      {
        key: 'clickworker',
        name: 'Clickworker API',
        description: 'Crowd tasks, data labeling, and testing workflows.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
        externalUrl: 'https://www.clickworker.com',
      },
      {
        key: 'microworkers',
        name: 'Microworkers',
        description: 'Data labeling, app testing, and image-tagging tasks.',
        integrationType: 'external',
        access: 'external_link',
        badge: 'Recommended',
        externalUrl: 'https://microworkers.com',
      },
      {
        key: 'toloka',
        name: 'Toloka API',
        description: 'AI training, moderation, and annotation work.',
        integrationType: 'api',
        access: 'external_link',
        badge: 'High Volume',
        externalUrl: 'https://toloka.ai',
      },
      {
        key: 'hive_micro',
        name: 'Hive Work API',
        description: 'AI data work and simple micro-earning tasks.',
        integrationType: 'api',
        access: 'external_link',
        badge: 'Fast Pay',
        externalUrl: 'https://hivemicro.com',
      },
      {
        key: 'online_task_runner',
        name: 'OTR API',
        description: 'Online task runner and web research task source.',
        integrationType: 'api',
        access: 'external_link',
        badge: 'New',
        externalUrl: 'https://www.onlinetaskrunner.com',
      },
    ],
  },
  ads_network: {
    key: 'ads_network',
    title: 'Ads / Ad Network',
    description: 'Ad SDKs, rewarded ad networks, and ad monetization partners by category.',
    providers: [
      {
        key: 'google_admob',
        name: 'Google AdMob',
        description: 'Rewarded and interstitial ad monetization for mobile surfaces.',
        integrationType: 'sdk',
        access: 'planned',
        badge: 'SDK',
      },
      {
        key: 'meta_audience_network',
        name: 'Meta Audience Network',
        description: 'Facebook/Meta ad network option for rewarded campaigns.',
        integrationType: 'sdk',
        access: 'planned',
        badge: 'SDK',
      },
      {
        key: 'ironsource',
        name: 'ironSource',
        description: 'Rewarded videos and app monetization inventory.',
        integrationType: 'sdk',
        access: 'planned',
        badge: 'Video Ads',
      },
      {
        key: 'tapjoy',
        name: 'Tapjoy',
        description: 'Rewarded ad and offer monetization partner.',
        integrationType: 'sdk',
        access: 'planned',
        badge: 'Rewarded',
      },
      {
        key: 'unity_ads',
        name: 'Unity Ads',
        description: 'Video ad placements for app-driven inventory.',
        integrationType: 'sdk',
        access: 'planned',
        badge: 'Video Ads',
      },
      {
        key: 'applovin',
        name: 'AppLovin',
        description: 'App monetization and rewarded ad stack.',
        integrationType: 'sdk',
        access: 'planned',
        badge: 'SDK',
      },
      {
        key: 'adgate_ads',
        name: 'AdGate Rewards',
        description: 'Rewarded installs and ad-driven conversion offers.',
        integrationType: 'api',
        access: 'internal_wall',
        badge: 'Live',
      },
      {
        key: 'ayet_ads',
        name: 'Ayet Studios',
        description: 'Performance ad network with rewarded install campaigns.',
        integrationType: 'api',
        access: 'internal_wall',
        badge: 'Live',
      },
    ],
  },
  offerwalls: {
    key: 'offerwalls',
    title: 'Offerwalls',
    description: 'Offerwall APIs and iframe/web wall integrations.',
    providers: [
      {
        key: 'ayetstudios',
        name: 'Ayet Studios',
        description: 'Install games, complete offers, and earn rewards.',
        integrationType: 'api',
        access: 'signed_wall',
        badge: 'Live',
      },
      {
        key: 'adgate',
        name: 'AdGate Rewards',
        description: 'App installs, signups, and promotional offers.',
        integrationType: 'api',
        access: 'signed_wall',
        badge: 'Live',
      },
      {
        key: 'tapjoy_offerwall',
        name: 'Tapjoy Offerwall',
        description: 'Offerwall inventory for app and signup conversions.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'wannads',
        name: 'Wannads',
        description: 'Rewarded offers and conversion-based tasks.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'adscend_media',
        name: 'Adscend Media Offerwall',
        description: 'Offerwall network for installs and engagement tasks.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'admobi_offerwall',
        name: 'AdMobi Offerwall',
        description: 'Additional mobile-focused offer inventory.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
      {
        key: 'rewards_offerwall',
        name: 'Rewards Offerwall',
        description: 'Reserved slot for another reward wall partner.',
        integrationType: 'api',
        access: 'planned',
        badge: 'Planned',
      },
    ],
  },
  cash_tasks: {
    key: 'cash_tasks',
    title: 'Cash Tasks',
    description: 'Sure jobs and cash task postings handled directly inside the platform.',
    providers: [
      {
        key: 'cash_task_board',
        name: 'Sure Jobs Board',
        description: 'Verified cash jobs posted directly on CashFlowConnect for users to browse and apply.',
        integrationType: 'internal',
        access: 'internal_link',
        badge: 'Sure Jobs',
        externalUrl: '/dashboard/tasks',
      },
      {
        key: 'verified_task_queue',
        name: 'Verified Cash Tasks',
        description: 'Manually reviewed cash tasks with clear requirements, payout bands, and completion checks.',
        integrationType: 'internal',
        access: 'internal_link',
        badge: 'Verified',
        externalUrl: '/dashboard/tasks',
      },
    ],
  },
};

const getCategoryProviderCatalog = () => CATEGORY_PROVIDERS;
const getCategoryProviders = (categoryKey) => CATEGORY_PROVIDERS[categoryKey] || null;

module.exports = {
  getCategoryProviderCatalog,
  getCategoryProviders,
};
