const { getPaymentPriorityForCountry } = require('./paymentStack');

const COUNTRIES = {
  KE: {
    name: 'Kenya',
    currency: 'KES',
    symbol: 'KSh',
    activationFee: 500,
    platformShare: 300,
    referralReward: 200,
    minWithdrawal: 200,
    paymentProvider: 'daraja',
    paymentRouting: getPaymentPriorityForCountry('KE'),
    flag: 'KE',
  },
  UG: {
    name: 'Uganda',
    currency: 'UGX',
    symbol: 'USh',
    activationFee: 16650,
    platformShare: 9990,
    referralReward: 6660,
    minWithdrawal: 6660,
    paymentProvider: 'paystack',
    paymentRouting: getPaymentPriorityForCountry('UG'),
    flag: 'UG',
  },
  TZ: {
    name: 'Tanzania',
    currency: 'TZS',
    symbol: 'TSh',
    activationFee: 11500,
    platformShare: 6900,
    referralReward: 4600,
    minWithdrawal: 4600,
    paymentProvider: 'jenga',
    paymentRouting: getPaymentPriorityForCountry('TZ'),
    flag: 'TZ',
  },
  ET: {
    name: 'Ethiopia',
    currency: 'ETB',
    symbol: 'Br',
    activationFee: 2250,
    platformShare: 1350,
    referralReward: 900,
    minWithdrawal: 900,
    paymentProvider: 'telebirr',
    paymentRouting: getPaymentPriorityForCountry('ET'),
    flag: 'ET',
  },
  GH: {
    name: 'Ghana',
    currency: 'GHS',
    symbol: 'GHS',
    activationFee: 18,
    platformShare: 10.8,
    referralReward: 7.2,
    minWithdrawal: 7.2,
    paymentProvider: 'paystack',
    paymentRouting: getPaymentPriorityForCountry('GH'),
    flag: 'GH',
  },
  NG: {
    name: 'Nigeria',
    currency: 'NGN',
    symbol: 'NGN',
    activationFee: 6500,
    platformShare: 3900,
    referralReward: 2600,
    minWithdrawal: 2600,
    paymentProvider: 'paystack',
    paymentRouting: getPaymentPriorityForCountry('NG'),
    flag: 'NG',
  },
};

const SUPPORTED_COUNTRY_CODES = Object.keys(COUNTRIES);

module.exports = { COUNTRIES, SUPPORTED_COUNTRY_CODES };
