const { getPaymentPriorityForCountry } = require('./paymentStack');

const COUNTRIES = {
  BJ: {
    name: 'Benin',
    currency: 'XOF',
    symbol: 'Fr',
    activationFee: 3000,
    platformShare: 1800,
    referralReward: 1200,
    minWithdrawal: 1200,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('BJ'),
    flag: 'BJ',
  },
  BF: {
    name: 'Burkina Faso',
    currency: 'XOF',
    symbol: 'Fr',
    activationFee: 3000,
    platformShare: 1800,
    referralReward: 1200,
    minWithdrawal: 1200,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('BF'),
    flag: 'BF',
  },
  CM: {
    name: 'Cameroon',
    currency: 'XAF',
    symbol: 'Fr',
    activationFee: 3200,
    platformShare: 1920,
    referralReward: 1280,
    minWithdrawal: 1280,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('CM'),
    flag: 'CM',
  },
  CG: {
    name: 'Congo-Brazzaville',
    currency: 'XAF',
    symbol: 'Fr',
    activationFee: 3200,
    platformShare: 1920,
    referralReward: 1280,
    minWithdrawal: 1280,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('CG'),
    flag: 'CG',
  },
  CD: {
    name: 'DRC (Dem. Rep. Congo)',
    currency: 'CDF',
    symbol: 'Fr',
    activationFee: 2500,
    platformShare: 1500,
    referralReward: 1000,
    minWithdrawal: 1000,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('CD'),
    flag: 'CD',
  },
  ET: {
    name: 'Ethiopia',
    currency: 'ETB',
    symbol: 'Br',
    activationFee: 2250,
    platformShare: 1350,
    referralReward: 900,
    minWithdrawal: 900,
    paymentProvider: 'telebirr',
    paymentRouting: getPaymentPriorityForCountry('ET'),
    flag: 'ET',
  },
  GA: {
    name: 'Gabon',
    currency: 'XAF',
    symbol: 'Fr',
    activationFee: 3200,
    platformShare: 1920,
    referralReward: 1280,
    minWithdrawal: 1280,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('GA'),
    flag: 'GA',
  },
  GH: {
    name: 'Ghana',
    currency: 'GHS',
    symbol: 'GHS',
    activationFee: 18,
    platformShare: 10.8,
    referralReward: 7.2,
    minWithdrawal: 7.2,
    paymentProvider: 'paystack',
    paymentRouting: getPaymentPriorityForCountry('GH'),
    flag: 'GH',
  },
  CI: {
    name: 'Ivory Coast (Côte d\'Ivoire)',
    currency: 'XOF',
    symbol: 'Fr',
    activationFee: 3000,
    platformShare: 1800,
    referralReward: 1200,
    minWithdrawal: 1200,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('CI'),
    flag: 'CI',
  },
  KE: {
    name: 'Kenya',
    currency: 'KES',
    symbol: 'KSh',
    activationFee: 500,
    platformShare: 300,
    referralReward: 200,
    minWithdrawal: 200,
    paymentProvider: 'daraja',
    paymentRouting: getPaymentPriorityForCountry('KE'),
    flag: 'KE',
  },
  LS: {
    name: 'Lesotho',
    currency: 'LSL',
    symbol: 'L',
    activationFee: 80,
    platformShare: 48,
    referralReward: 32,
    minWithdrawal: 32,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('LS'),
    flag: 'LS',
  },
  MW: {
    name: 'Malawi',
    currency: 'MWK',
    symbol: 'MK',
    activationFee: 850,
    platformShare: 510,
    referralReward: 340,
    minWithdrawal: 340,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('MW'),
    flag: 'MW',
  },
  MZ: {
    name: 'Mozambique',
    currency: 'MZN',
    symbol: 'MT',
    activationFee: 3200,
    platformShare: 1920,
    referralReward: 1280,
    minWithdrawal: 1280,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('MZ'),
    flag: 'MZ',
  },
  NG: {
    name: 'Nigeria',
    currency: 'NGN',
    symbol: 'NGN',
    activationFee: 6500,
    platformShare: 3900,
    referralReward: 2600,
    minWithdrawal: 2600,
    paymentProvider: 'paystack',
    paymentRouting: getPaymentPriorityForCountry('NG'),
    flag: 'NG',
  },
  RW: {
    name: 'Rwanda',
    currency: 'RWF',
    symbol: 'Fr',
    activationFee: 6500,
    platformShare: 3900,
    referralReward: 2600,
    minWithdrawal: 2600,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('RW'),
    flag: 'RW',
  },
  SN: {
    name: 'Senegal',
    currency: 'XOF',
    symbol: 'Fr',
    activationFee: 3000,
    platformShare: 1800,
    referralReward: 1200,
    minWithdrawal: 1200,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('SN'),
    flag: 'SN',
  },
  SL: {
    name: 'Sierra Leone',
    currency: 'SLL',
    symbol: 'Le',
    activationFee: 13000,
    platformShare: 7800,
    referralReward: 5200,
    minWithdrawal: 5200,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('SL'),
    flag: 'SL',
  },
  TZ: {
    name: 'Tanzania',
    currency: 'TZS',
    symbol: 'TSh',
    activationFee: 11500,
    platformShare: 6900,
    referralReward: 4600,
    minWithdrawal: 4600,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('TZ'),
    flag: 'TZ',
  },
  UG: {
    name: 'Uganda',
    currency: 'UGX',
    symbol: 'USh',
    activationFee: 16650,
    platformShare: 9990,
    referralReward: 6660,
    minWithdrawal: 6660,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('UG'),
    flag: 'UG',
  },
  ZM: {
    name: 'Zambia',
    currency: 'ZMW',
    symbol: 'ZK',
    activationFee: 20,
    platformShare: 12,
    referralReward: 8,
    minWithdrawal: 8,
    paymentProvider: 'pawapay',
    paymentRouting: getPaymentPriorityForCountry('ZM'),
    flag: 'ZM',
  },
};

const SUPPORTED_COUNTRY_CODES = Object.keys(COUNTRIES);

module.exports = { COUNTRIES, SUPPORTED_COUNTRY_CODES };
