const COUNTRIES = {
  KE: {
    name: 'Kenya',
    currency: 'KES',
    symbol: 'KSh',
    activationFee: 500,
    platformShare: 300,
    referralReward: 200,
    minWithdrawal: 200,
    paymentProvider: 'mpesa',
    flag: '🇰🇪',
  },
  UG: {
    name: 'Uganda',
    currency: 'UGX',
    symbol: 'USh',
    activationFee: 16650,
    platformShare: 9990,
    referralReward: 6660,
    minWithdrawal: 6660,
    paymentProvider: 'mtn',
    flag: '🇺🇬',
  },
  TZ: {
    name: 'Tanzania',
    currency: 'TZS',
    symbol: 'TSh',
    activationFee: 11500,
    platformShare: 6900,
    referralReward: 4600,
    minWithdrawal: 4600,
    paymentProvider: 'vodacom',
    flag: '🇹🇿',
  },
  ET: {
    name: 'Ethiopia',
    currency: 'ETB',
    symbol: 'Br',
    activationFee: 2250,
    platformShare: 1350,
    referralReward: 900,
    minWithdrawal: 900,
    paymentProvider: 'telebirr',
    flag: '🇪🇹',
  },
  GH: {
    name: 'Ghana',
    currency: 'GHS',
    symbol: 'GH₵',
    activationFee: 18,
    platformShare: 10.8,
    referralReward: 7.2,
    minWithdrawal: 7.2,
    paymentProvider: 'flutterwave',
    flag: '🇬🇭',
  },
  NG: {
    name: 'Nigeria',
    currency: 'NGN',
    symbol: '₦',
    activationFee: 6500,
    platformShare: 3900,
    referralReward: 2600,
    minWithdrawal: 2600,
    paymentProvider: 'flutterwave',
    flag: '🇳🇬',
  },
};

const SUPPORTED_COUNTRY_CODES = Object.keys(COUNTRIES);

module.exports = { COUNTRIES, SUPPORTED_COUNTRY_CODES };
